### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by sa-lee** [dicook/wiley-isghdd#1]
@dicook and I discussed that is probably better for us to just pull in figures from previous work. One thing to note is that if you do this we need to ask the original journals permission to reprint.

**Comment by sa-lee** [comment]
pinging @uschiLaa and @huizezhang-sherry could you please put in the remaining figures for the notation section https://github.com/dicook/wiley-isghdd/blob/ae231bbde6d9335e179d95e7bba1441c1a4a90b6/paper.Rmd#L124

**Comment by sa-lee** [comment]
pinging @dicook is it possible to get pdfs for the following figures from the ggobi book:

- Fig 2.12 or 2.15 or 2.16 on p36 or p41 for brushing section
- Fig.  5.3. on p109 for brush and spin and section

**Comment by dicook** [comment]
figures are their now - they are composite figures, put together in the latex

> On 15 Mar 2021, at 4:13 pm, Stuart Lee ***@***.***> wrote:
> 
> 
> pinging @dicook is it possible to get pdfs for the following figures from the ggobi book:
> 
> 	• Fig 2.12 or 2.15 or 2.16 on p36 or p41 for brushing section
> 	• Fig. 5.3. on p109 for brush and spin and section
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by sa-lee** [comment]
@nspyrison @uschiLaa @huizezhang-sherry could you please modify your figure captions with the citation for the relevant paper. i.e. something along the lines of "Adapted from Smith et al. 2021 (Figure x)" you can do this manually if that's easiest

**Comment by sa-lee** [comment]
@dicook  there's a few outstanding things for your figures. For the clustering picture, the layout seems off as there is a blank space on the right in panel A. Is this intentional?

@nspyrison was your figure taken from your spinifex paper? Can you let me know and I'll adjust the caption accordingly.

**Comment by sa-lee** [comment]
@dicook can you upload the tour_path.png to git please?

**Comment by dicook** [comment]
Done

> On 14 Apr 2021, at 3:34 pm, Stuart Lee ***@***.***> wrote:
> 
> 
> @dicook can you upload the tour_path.png to git please?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by natydasilva** [comment]
Hi @sa-lee, I've included this comment in  .Rmd file but I think maybe is better to include here.

FIGURE 3: Comparison of structure perception....,
 I think you are using Dark2 palette but in the figure caption you mention green and brown, I'm not colorblind but I check the palette description and the color is #D95F02 (https://www.colorhexa.com/d95f02) color description: Vivid orange. If this is correct, you should  replace  "brown" by orange in  Figure 3  caption and in  Figure 3 comments in page 4 (two brown each)

**Comment by sa-lee** [comment]
Thanks @natydasilva, @dicook made these figures so will leave it up to her to change the color description.

**Comment by dicook** [comment]
I’m ok with changing brown to orange

> On 15 Apr 2021, at 10:12 am, Stuart Lee ***@***.***> wrote:
> 
> 
> Thanks @natydasilva, @dicook made these figures so will leave it up to her to change the color description.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

cheers,
Di

---
Dianne Cook
***@***.***

**Comment by natydasilva** [comment]
@sa-lee I just some additional comment about Figures, maybe something is useful:

Figure 4:   Huber's plot (left plots) of the penguins data....Maybe will be better to  capital letter for axis labels (Count, Group and Best projected data). And maybe use the same Dark2 palette.

Figure 5: "Various displays of the projections..." Maybe increasing the axis text size will be good to see the axis labels 

Figure 6: "A comparison of guided....." and Figure 7:"Still views of a tour showing the space...." maybe change the color (brown) because are difficult to distinguish. Similar problem in Figure 12: Three  projections  from  a  manual  tour  where  variable  "bl" .... "  Not sure if you have selected a colorblind friendly palette but I check these Figures with a colorblind person (small sample but...) and was very  difficult  for him to distinguish the mixed colors.

**Comment by sa-lee** [comment]
Thanks for the comments, regarding the color issues I'll let @dicook make the call as to whether we want to change them, for fig 6/7 I don't think the color is a big issue since the main idea is just seeing the path. With figure 5 I don't think the axes are super important here, since we are just saying what types of geoms are possible.
